[project]
name = "brugerluk-nfs"
version = "0.3.3"
description = "Lukker NFS-brugere for medarbejdere, der er registreret til nedlukning i BOSS"
license = "MIT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "automation-server-client",
    "boss-client",
    "nfs-client",
    "odk-tools",
]

[tool.uv.sources]
nfs-client = { git = "https://github.com/odense-rpa/nfs-client.git" }
boss-client = { git = "https://github.com/odense-rpa/boss-client.git" }
odk-tools = { git = "https://github.com/odense-rpa/odk-tools.git" }
automation-server-client = { git = "https://github.com/odense-rpa/automation-server-client.git" }

[tool.ruff]
line-length = 88

[dependency-groups]
dev = [
    "ruff>=0.16.9",
]
